spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discord_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
